### PR TITLE
add char16be

### PR DESCRIPTION
**Pull request by nraynaud**

### CODE REVIEW

**Comment by natevw** [comment]
Thanks @nraynaud for this pull request!

However, I'm not excited about the addition of `swapBytesPairs`. Right now there's a serious showstopper in that you modify the source buffer, which the user may not be expecting!

While this could be fixed by adding a second call to swap back before `b2v` returns, I can't help but think that if this is something that you really need, we should work to get a 'utf16be' encoding into node.js itself. (I don't know why they don't include it, but you could start simply by filing an issue on https://github.com/nodejs/node and see what they say?)

**Comment by nraynaud** [comment]
Big endian is a complete non-starter in node: https://github.com/nodejs/node-v0.x-archive/issues/1684

I guess I'll create a temporary buffer to flip the bytes then.

Envoyé de mon iPhone

**Comment by julien-f** [comment]
Any news on this?

**Comment by natevw** [comment]
How common is this format? Is there a common need for this, or just for API symmetry?

I'm still not terribly excited to go beyond what node's own Buffer features, but willing to consider it if there's a compelling use case for it (and assuming some issues with the patch are cleaned up, namely that as it is right now it modifies the source buffer, and also introduces a `b.fill(0)` to `char16le` that might not be backwards-compatible).

**Comment by nraynaud** [comment]
Big endian is also referred as "network byte order", it's the most common byte ordering in interchange format specifications. It's the default byte order of ASN.1, which means most of the internet protocols.

**Comment by natevw** [comment]
@nraynaud Sure, but how much *text* is encoded in UTF16BE? As far as I can tell, ASN.1 uses UTF-8 as do many many other Internet protocols as they were typically "upgraded" from ASCII. Do you have a specific situation where you unavoidably need this, or are you simply trying to make this API "complete" in a way that node's Buffer is not?

@julien-f I see you are part of the Node-SMB project…is there a need for UTF16BE there? All I found in a quick search this [MS-CIFS](https://msdn.microsoft.com/en-us/library/ee442084.aspx) documentation that states "All Unicode characters MUST be in UTF-16**LE** encoding." [emphasis mine]

Again, I'm not completely opposed to it — I just want to make sure that we really really need UTF16BE in struct-fu even though it's not apparently worth v8 or node supporting natively.

**Comment by nraynaud** [comment]
I used in when reading VHD files https://github.com/nraynaud/xo-vhdmount/blob/master/src/vhd.js#L88

I'm sorry, my previous answer was out of context, it's been a while, and I though we were talking about 16bits number, and I realize we are talking chars.

So, it's mostly a compatibility issue with standards of a certain era.

**Comment by julien-f** [comment]
@natevw The Node-SMB project is quite new (created a week ago :stuck_out_tongue: ) and I have not written much code, I simply created it to group SMB related projects because some of them were no longer correctly maintained.

I don't know if UTF-16 BE is used much IRL, but it is used in the VHD format, like @nraynaud said.

**Comment by julien-f** [comment]
@natevw What's your opinion on this?

**Comment by nraynaud** [comment]
@natevw I changed the code to avoid modifying the input buffer. I hope you warm up to the idea of merging.

**Comment by natevw** [comment]
Getting there! I'd almost rather just see a swap/read/swap as originally suggested but the temporary copy works too — this has the advantage of not needing extra memory if the structs are large, but it may be that it ends up avoidng an even larger copy-on-write or something. Basically what you have should work if you want to leave it, since most use cases probably are shortish strings anyway, and we can always optimize later if someone needs it.

The remaining issue now is that you've added `b.fill(0)` in two places, where it should not be needed. [I mis-spoke above when I implied this was a change to behavior.] The base `bytefield` actually already fills in any leftover space with zeroes — so you should remove that from both the original `utf16le` where you added it, and also the new `utf16be`. Then in your new implementation, instead of returning a buffer from `vTb` you need to return the number of bytes written, something like this:

```
 +    vTb: function (v,b) {
 +        v || (v = '');
 +        var len = b.write(v, 'utf16le');
 +        swapBytesPairs(b);
 +        return len;
 +    }
```

…then the existing `bytefield` logic should 0-fill for you.

**Comment by natevw** [comment]
Thanks for sticking with this! I've merged in your commits and will release it shortly. Really appreciate you updating the tests and docs to keep them up to date as well :-)

**Comment by natevw** [comment]
Published as struct-fu@1.1.0, thanks again!

**Pull request merged**
